done

diff --git a/slumbot b/slumbot
--- a/slumbot
+++ b/slumbot
@@ -1,104 +1,142 @@
 #!/usr/bin/env bash
 # shellcheck disable=2034,2155,2162
 
-api() {
-    RESPONSE=$(curl -s "https://slumbot.com/api/$1" --header content-type:\ application/json -d "$2")
-    local message=$(jq -r '.error_msg // ""' <<<"$RESPONSE")
-    if [[ -n $message ]]; then
-        printf "%s\n" "$message"
-    else
-        BODY=$RESPONSE
-    fi
-}
-api new_hand {}
-TOKEN=$(jq -r '"\"token\":\"\(.token)\""' <<<"$BODY")
-post() {
-    if [[ -n $1 ]]; then
-        api act "{$TOKEN,\"incr\":\"$1\"}"
-    else
-        api new_hand "{$TOKEN}"
-    fi
-}
-DIFFERENCE="/ 10 | if . < 0 then . else \"+\(.)\" end else \"\" end"
-difference() {
-    local me=$(jq -r "if .$1 != null then .$1 $DIFFERENCE" <<<"$BODY")
-    printf "\e[1E\e[10C%-4s \e[2m%s\e[0m" "$me" "$(jq -r "if .$2 != null then (\$me | tonumber) - .$2 $DIFFERENCE" --arg me "$me" <<<"$BODY")"
-}
+trap 'printf "\e[9;0f\e[?25h"' 0
 BUTTON="Ⓓ "
-card() {
-    if [[ -n $1 ]]; then
-        case ${1:1:1} in
-        s) printf "\e[30m%s♤\e[0m" "${1:0:1}" ;;
-        h) printf "\e[31m%s♡\e[0m" "${1:0:1}" ;;
-        d) printf "\e[34m%s♢\e[0m" "${1:0:1}" ;;
-        c) printf "\e[32m%s♧\e[0m" "${1:0:1}" ;;
-        esac
-    else
-        printf "  "
-    fi
+REGEX='"action":\s*"([/0-9fkcb]*)",\s*"client_pos":\s*([01]),\s*"hole_cards":\s*\[\s*"([2-9TJQKA][shdc])",\s*"([2-9TJQKA][shdc])"\s*\],\s*"board":\s*\[[[:space:]"]*([2-9TJQKA][shdc])?[[:space:]",]*([2-9TJQKA][shdc])?[[:space:]",]*([2-9TJQKA][shdc])?[[:space:]",]*([2-9TJQKA][shdc])?[[:space:]",]*([2-9TJQKA][shdc])?[[:space:]"]*\],?(\s*"bot_hole_cards":\s*\[\s*"([2-9TJQKA][shdc])",\s*"([2-9TJQKA][shdc])"\s*\],\s*"winnings":\s*(-?[0-9]+),\s*"won_pot":\s*-?[0-9]+,\s*"session_num_hands":\s*(-?[0-9]+),\s*"baseline_winnings":\s*(-?[0-9]+),\s*"session_total":\s*(-?[0-9]+),\s*"session_baseline_total":\s*(-?[0-9]+))?'
+ERROR='"error_msg":\s*"([[:print:]]+)"'
+CALLED='b([0-9]+)c'
+UNCALLED='([0-9]+)?b([0-9]+)$'
+CURRENT='([/kcf]|b[0-9]+)?([/kcf]|b[0-9]+)?([/kcf]|b[0-9]+)?$'
+cards() {
+    for card; do
+        if [[ -n $card ]]; then
+            case ${card:1:1} in
+            s) local suit="0♤" ;;
+            h) local suit="1♡" ;;
+            d) local suit="4♢" ;;
+            c) local suit="2♧" ;;
+            esac
+            printf "\e[3%sm%s%s\e[0m\e[2C" "${suit:0:1}" "${card:0:1}" "${suit:1:1}"
+        else
+            printf "  \e[2C"
+        fi
+    done
 }
-
-printf "\e[2J\e[H╭──╮╭──╮
-│  ││  │
-╰──╯╰──╯
->        ┌──────────────────────┐
-┌──────┐ │ ╭──╮╭──╮╭──╮╭──╮╭──╮ │
-│      │ │ │  ││  ││  ││  ││  │ │
-└──────┘ │ ╰──╯╰──╯╰──╯╰──╯╰──╯ │
->        └──────────────────────┘
-╭──╮╭──╮   
-│  ││  │
-╰──╯╰──╯
-"
-STATE=1
-update() {
-    local hands=$(jq -r '(.hole_cards // []) + (.bot_hole_cards // []) | join("")' <<<"$BODY")
-    local board=$(jq -r '.board | join("")' <<<"$BODY")
-    local position=$(jq '.client_pos' <<<"$BODY")
-    local action=$(jq '"/b50b100" + .action' <<<"$BODY")
-    local calls=$(jq '[match("(?<=b)\\d+(?=0c)"; "g").string | tonumber] | add // 0' <<<"$action")
-    local act_1=$(jq -r 'match("/(?:[kcf]|b\\d+)(?:(?:[kcf]|b\\d+){2})*([kcf]|b\\d+?)0?(?:[kcf]|b\\d+)?$").captures[0].string' <<<"$action")
-    local act_2=$(jq -r 'match("/(?:(?:[kcf]|b\\d+){2})*([kcf]|b\\d+?)0?(?:[kcf]|b\\d+)?$").captures[0].string' <<<"$action")
-    local pot=$(jq '. * 2 + try ($act_1 | tonumber) catch 0 + try ($act_2 | tonumber) catch 0' --arg act_1 "${act_1#b}" --arg act_2 "${act_2#b}" <<<"$calls")
-    printf "\e[H\e[9B\e[1C"
-    card "${hands:0:2}"
-    printf "\e[2C"
-    card "${hands:2:2}"
-    printf "\e[1C%s" "${BUTTON:$position:1}"
-    printf "\e[8F\e[1C"
-    card "${hands:4:2}"
-    printf "\e[2C"
-    card "${hands:6:2}"
-    printf "\e[1C%s" "${BUTTON:$((position ^ 1)):1}"
-    printf "\e[4E\e[2C%-4s\e[6C" "$pot"
-    card "${board:0:2}"
-    printf "\e[2C"
-    card "${board:2:2}"
-    printf "\e[2C"
-    card "${board:4:2}"
-    printf "\e[2C"
-    card "${board:6:2}"
-    printf "\e[2C"
-    card "${board:8:2}"
-    if [[ $position == 0 ]]; then
-        printf "\e[2F\e[2C%-5s\e[4E\e[2C%-5s" "$act_2" "$act_1"
-        local chips=$(jq '2000 - . - try ($act_1 | tonumber) catch 0' --arg act_1 "${act_1#b}" <<<"$calls")
-    else
-        printf "\e[2F\e[2C%-5s\e[4E\e[2C%-5s" "$act_1" "$act_2"
-        local chips=$(jq '2000 - . - try ($act_2 | tonumber) catch 0' --arg act_2 "${act_2#b}" <<<"$calls")
-    fi
-    printf "\e[1E\e[10C%s" "$chips"
-    difference "winnings" "baseline_winnings"
-    difference "session_total" "session_baseline_total"
-    printf "\e[H\e[12B"
-}
-
 main() {
-    printf "\e[?25l"
+    printf "\e[?25l\e[2J\e[H╭──╮╭──╮
+│  ││  │
+╰──╯╰──╯
+┌──────┐  ╭──╮╭──╮╭──╮╭──╮╭──╮
+│      │  │  ││  ││  ││  ││  │
+└──────┘  ╰──╯╰──╯╰──╯╰──╯╰──╯
+╭──╮╭──╮
+│  ││  │
+╰──╯╰──╯\e[H"
+
+    local header="content-type: application/json"
+    local body=$(curl -s https://slumbot.com/api/new_hand --header "$header" -d {})
+    local token="\"token\":\"${body: -38:36}\""
     while true; do
-        update
-        read command
-        post "$command"
+        if [[ $body =~ $REGEX ]]; then
+            # position
+            local position=${BASH_REMATCH[2]}
+            printf "\e[2;9f%s\e[8;9f%s" "${BUTTON:$position:1}" "${BUTTON:$((position ^ 1)):1}"
+
+            # hole cards
+            printf "\e[8;2f"
+            cards "${BASH_REMATCH[3]}" "${BASH_REMATCH[4]}"
+
+            # board
+            printf "\e[5;12f"
+            cards "${BASH_REMATCH[5]}" "${BASH_REMATCH[6]}" "${BASH_REMATCH[7]}" "${BASH_REMATCH[8]}" "${BASH_REMATCH[9]}"
+
+            # bot hole cards
+            printf "\e[2;2f"
+            cards "${BASH_REMATCH[11]}" "${BASH_REMATCH[12]}"
+
+            # stats
+            if [[ ${BASH_REMATCH[10]} ]]; then
+                local result=${BASH_REMATCH[13]}
+                local hands=${BASH_REMATCH[14]}
+                local bot_result=${BASH_REMATCH[15]}
+                local total=${BASH_REMATCH[16]}
+                local bot_total=${BASH_REMATCH[17]}
+                [[ ${result:0:1} != - ]] && local result="+$result"
+                [[ ${bot_result:0:1} != - ]] && local bot_result="+$bot_result"
+                [[ ${total:0:1} != - ]] && local total="+$total"
+                [[ ${bot_total:0:1} != - ]] && local bot_total="+$bot_total"
+                printf "\e[1;12f%-5s\e[2;12f%-15s\e[3;12f%-15s" "$hands" "$total ($bot_total)" "$result ($bot_result)"
+            else
+                printf "\e[1;12f\e[0K\e[2;12f\e[0K\e[3;12f\e[0K"
+            fi
+
+            # action
+            local action="/b50b100${BASH_REMATCH[1]}"
+            if [[ $action =~ $CURRENT ]]; then
+                local index=6
+                for match in "${BASH_REMATCH[@]:1}"; do
+                    case $match in
+                    "") local act="" ;;
+                    /)
+                        local lengther=${action//\//}
+                        case $((${#action} - ${#lengther})) in
+                        1) local act="(preflop)" ;;
+                        2) local act="(flop)" ;;
+                        3) local act="(turn)" ;;
+                        4) local act="(river)" ;;
+                        esac
+                        ;;
+                    f) local act=fold ;;
+                    k) local act=check ;;
+                    c) local act=call ;;
+                    *)
+                        local act="${match/b/}"
+                        act=$((act / 10))
+                        ;;
+                    esac
+                    [[ $act ]] && printf "\e[%s;12f> %-9s" "$((++index))" "$act"
+                done
+            fi
+
+            # pot
+            local pot=0
+            local size=150
+            if [[ $action =~ $UNCALLED ]]; then
+                pot=$((pot + BASH_REMATCH[1] + BASH_REMATCH[2]))
+                [[ ${BASH_REMATCH[2]} -gt $size ]] && size=${BASH_REMATCH[2]}
+            fi
+            while [[ $action =~ $CALLED ]]; do
+                pot=$((pot + BASH_REMATCH[1] * 2))
+                action=${action/${BASH_REMATCH[0]}/}
+            done
+            printf "\e[5;3f%-5s" "$((pot / 10))"
+
+            # clear message
+            printf "\e[10;0f\e[0K"
+        elif [[ $body =~ $ERROR ]]; then
+            printf "\e[10;0f%s" "${BASH_REMATCH[1]}"
+        else
+            printf "\e[10;1f%s" "$body"
+        fi
+        read -rn1 key
+        local chips=$((20000 - pot / 2))
+        local path=act
+        local incr=""
+        case $key in
+        a) path=new_hand ;;
+        s) incr=f ;;
+        d) incr=k ;;
+        f) incr=c ;;
+        j) incr="b$((size * 2))" ;;
+        k) incr="b$((pot / 2))" ;;
+        l) incr="b$pot" ;;
+        \;) incr="b$chips" ;;
+        q) return ;;
+        esac
+        [[ ${incr:0:1} == b ]] && [[ ${incr:1} -gt $chips ]] && incr="b$chips"
+        [[ $incr ]] && incr=",\"incr\":\"$incr\""
+        body=$(curl -s "https://slumbot.com/api/$path" --header "$header" -d "{$token$incr}")
     done
 }
 
